# profiles.yml file example for dbt with ClickHouse
dbt_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "{{ env_var('DBT_CLICKHOUSE_HOST') }}"
      port: "{{ env_var('DBT_CLICKHOUSE_PORT') | int }}"
      user: "{{ env_var('DBT_CLICKHOUSE_USER') }}"
      password: "{{ env_var('DBT_CLICKHOUSE_PASSWORD') }}"
      secure: True
