name: linter
on:
  # Can be manually triggered
  workflow_dispatch: {}
  # Triggered on each pull request to main
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-bookworm
    services:
      postgres:
        image: yandex/clickhouse-server
        env:
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: HgBUQH4FtQS_M
          CLICKHOUSE_DB: default 
        ports:
          - 8443:8443
        options: >-
          --health-cmd="clickhouse client --query='SELECT 1'"
          --health-interval 10s
          --health-timeout 5s

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run linting checks. Exit code 1 if linter failed
        run: |
          bash ./bin/linter.sh